
motordriver_node:
  ros__parameters:
    simulation: True
odom_node:
  ros__parameters:
    wheel_radius: 0.0335
    wheel_base: 0.215
    ticks_per_revolution: 2000
cmd_vel_node:
  ros__parameters:
    wheel_radius: 0.0335
    wheel_base: 0.215
    ticks_per_revolution: 2000
