graph TD
    classDef hardware fill:#FFCCBC,stroke:#BF360C,stroke-width:2px,color:#000;
    classDef logic fill:#BBDEFB,stroke:#0D47A1,stroke-width:2px,color:#000;
    classDef display fill:#FFCCBC,stroke:#0D47A1,stroke-width:2px,color:#000;
    classDef container fill:#FFFFFF,stroke:#666,stroke-width:2px,stroke-dasharray: 5 5;

    %% ----------- SYSTEM -----------
    subgraph UWB_Positioning [UWB Positioning]
        direction TB

        %% --- HARDWARE ---
        subgraph Hardware_Layer [Hardware]
            RPi5[Raspberry Pi 5]:::hardware
            UWB[Module UWB DWM1001]:::hardware
        end

        %% --- ROS2 ---
        subgraph ROS_Layer [ROS2 Architecture]
            Driver[Driver Node: Read Serial]:::logic
            Helper[Estimate position using Least Square / Kalman]:::logic
            Compare[Compare Results]:::logic
        end

        %% --- VISUALIZATION ---
        subgraph Visual_Layer [Visualization]
            GUI[Visualize using Numpy]:::display
        end
    end

    %% ----------- CONNECTIONS -----------
    RPi5 -- UART Connection --> UWB
    UWB -- Serial Data --> Driver

    Driver -- Raw Ranges --> Helper
    Helper -- Estimated Position --> Compare

    Driver -.-> |Reference Decawave pos| Compare

    Compare -- Position & Error --> GUI