uwb_tracking_dwm1001:  
  ros__parameters:      
    port: "/dev/ttyACM0"
    tag_name: "DW58B6"
    use_network: True
    network: "0x59D9"
    verbose: True
    read_rate: 10.0
    tag_id: "0xDECAC2066165878F"
    mac_id: "C4:22:04:B9:DE:53"
    use_least_square: False
    least_square_max_iterations: 10
    least_square_tolerance: 0.01
